### ISSUE TITLE
[User Story]: Test ttk codeblock

### ISSUE THREAD

**Issue by DanHugoDanHugo** [DanHugoDanHugo/edison-debian-chroot#17]
### As a …

Organization Member

### Short Description

# H1 Heading
### Full Description of the Reported Bug as Received

The full description

### Reporter Attribution

- [ ] Contact Information Available
- [X] Contact Information Redacted For Privacy
- [ ] Contact Reporter with Status Updates
- [ ] Attribution Information Available
- [ ] Attribute Contribution(s) to Reporter

### Linked Issues

- [ ] :defect #16 

### Linked Issues

```ttl
:defect #16
```

**Comment by DanHugoDanHugo** [comment]
```yaml
valkey:
  effort: 10
  expertise: 3
```
